[package]
name = "nn-examples"
version = "0.1.0"
edition = "2021"

[dependencies]
gpu-accel = { path = "../gpu-accel" }
pollster = { workspace = true }

[[bin]]
name = "tensor_ops"
path = "src/tensorops.rs"

[[bin]]
name = "mnist_jp"
path = "src/mnist_jp.rs"
