[package]
name = "nn-backbone"
version = "0.1.0"
edition = "2021"
description = "simple Neural Network Backbone for examples"

[dependencies]
gpu-accel = { path = "../gpu-accel" }

pollster = "*"
rand = "*"
tokio = { version = "1.0", features = ["full"] }
lazy_static = "1.4"
wgpu = "*"
